### ISSUE TITLE
[signup-page]

### ISSUE THREAD

**Issue by kimsayhi** [FE8-team5/ESCape#15]
## ✏️ 어떤 기능인가요?
> 현재 개발하고자 하는 기능에 대해 설명해주세요
- 

## ✅ 작업 상세 내용
- [x] #32
- [x] #35
    - 이메일 입력창에서 blur 될 때, 아무것도 적혀있지 않다면 다음 에러 메세지를 보여줍니다. “이메일은 필수 입력입니다.”
    - 이메일 입력창에서 blur 될 때, 이메일 형식이 아닐 경우 이메일 입력창에 다음 에러 메세지를 보여줍니다. “이메일 형식으로 작성해 주세요.”
    - 닉네임 입력창에서 blur 될 때, 아무것도 적혀있지 않다면 다음 에러 메세지를 보여줍니다. “닉네임은 필수 입력입니다.”
    - 닉네임 입력창에서 blur 될 때, 글자수가 20자를 초과하면 다음 에러 메세지를 보여줍니다. “닉네임은 최대 20자까지 가능합니다.”
    - 비밀번호 입력창에서 blur 될 때, 아무것도 적혀있지 않다면 다음 에러 메세지를 보여줍니다. “비밀번호는 필수 입력입니다.”
    - 비밀번호 입력창에서 blur 될 때, 비밀번호가 8자 미만일 경우 다음 에러 메세지를 보여줍니다. “비밀번호는 최소 8자 이상입니다.”
    - 비밀번호 입력창에서 blur 될 때, 숫자,영문,특수문자(!@#$%^&*) 로만 이루어지지 않았을 경우 다음 에러 메세지를 보여줍니다. “비밀번호는 숫자, 영문, 특수문자로만 가능합니다.”
    - 비밀번호 확인 입력창에서 blur 될 때, 아무것도 적혀있지 않다면 다음 에러 메세지를 보여줍니다. “비밀번호 확인을 입력해주세요.”
    - 비밀번호 확인 입력창에서 blur 될 때, 비밀번호 확인 입력창이 비어있지 않은 상태이며 비밀번호 입력값과 같지 않다면 다음 에러 메세지를 보여줍니다. “비밀번호가 일치하지 않습니다.”
- [x] #39
- [x] #40

**Comment by naynara87** [comment]
요구사항에 없지만 추후 이메일 중복과 같은 디테일 개선 해보겠습니다.
